In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('HousePredict_MultipleVariable.csv')
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
import math
median_bedrooms = math.floor(df.Bedrooms.median())
median_bedrooms

3

In [4]:
df.Bedrooms = df.Bedrooms.fillna(median_bedrooms)
df.Bedrooms

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: Bedrooms, dtype: float64

In [5]:
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
rg = linear_model.LinearRegression()
model = rg.fit(df[['Area','Bedrooms','Age']],df.Price)
model

LinearRegression()

In [7]:
rg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [8]:
rg.intercept_

383724.9999999998

In [9]:
rg.predict([[4003,5,45]])

array([495886.75])

In [10]:
import pickle

In [11]:
with open ('model_pickle','wb') as f:
    pickle.dump(model,f)

In [12]:
with open('model_pickle','rb') as f:
    mp =  pickle.load(f)
    
mp.predict([[5000,5,32]])

array([721450.])

In [13]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)