In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

from sklearn.datasets import load_digits


digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [4]:
Lr = LogisticRegression()
Lr.fit(x_train, y_train)
Lr.score(x_test, y_test)

C:\Users\TOBY CYBERWORLD\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [5]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9777777777777777

In [6]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9555555555555556

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [10]:
get_score(RandomForestClassifier(n_estimators = 40), x_train, x_test, y_train, y_test)

0.9555555555555556

In [11]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [27]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

In [32]:
scores_l

[0.0, 0.0, 0.0]

In [24]:
scores_svm

[0.0, 0.0, 0.0]

In [25]:
scores_rf

[0.0, 0.0, 0.0]

In [33]:
from sklearn.model_selection import cross_val_score

In [35]:
 cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\TOBY CYBERWORLD\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\TOBY CYBERWORLD\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [36]:
 cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [42]:
 cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data, digits.target)

array([0.92777778, 0.90277778, 0.94707521, 0.98050139, 0.91364903])